IF "%WWW_FRONTEND_BASE_DIRECTORY%" == "" GOTO NO_WWW_FRONTEND_BASE_DIRECTORY
IF "%AUTOMATIC_BATCH_INSTALLER_LOG_FILE%" == "" set AUTOMATIC_BATCH_INSTALLER_LOG_FILE=output.log

@ECHO net stop QuickQuotation_FrontEnd(8000) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net stop QuickQuotation_FrontEnd(8000) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net stop QuickQuotation_FrontEnd(8001) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net stop QuickQuotation_FrontEnd(8001) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net stop QuickQuotation_FrontEnd(8002) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net stop QuickQuotation_FrontEnd(8002) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net stop QuickQuotation_FrontEnd(8003) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1 
net stop QuickQuotation_FrontEnd(8003) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO cd %~dp0 >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
cd %~dp0 >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO rmdir /S /Q %WWW_FRONTEND_BASE_DIRECTORY%\dist >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
rmdir /S /Q %WWW_FRONTEND_BASE_DIRECTORY%\dist >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO rmdir /S /Q %WWW_FRONTEND_BASE_DIRECTORY%\node_modules >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
rmdir /S /Q %WWW_FRONTEND_BASE_DIRECTORY%\node_modules >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO mkdir %WWW_FRONTEND_BASE_DIRECTORY%\dist >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
mkdir %WWW_FRONTEND_BASE_DIRECTORY%\dist >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO mkdir %WWW_FRONTEND_BASE_DIRECTORY%\node_modules >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
mkdir %WWW_FRONTEND_BASE_DIRECTORY%\node_modules >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO robocopy /nfl /ndl %~dp0 %WWW_FRONTEND_BASE_DIRECTORY%\ server.js >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
robocopy /nfl /ndl %~dp0 %WWW_FRONTEND_BASE_DIRECTORY%\ server.js >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO robocopy /nfl /ndl %~dp0 %WWW_FRONTEND_BASE_DIRECTORY%\ package.json >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
robocopy /nfl /ndl %~dp0 %WWW_FRONTEND_BASE_DIRECTORY%\ package.json >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO robocopy /nfl /ndl /E %~dp0dist\ %WWW_FRONTEND_BASE_DIRECTORY%\dist\ >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
robocopy /nfl /ndl /E %~dp0dist\ %WWW_FRONTEND_BASE_DIRECTORY%\dist\ >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO robocopy /nfl /ndl /E %~dp0node_modules\ %WWW_FRONTEND_BASE_DIRECTORY%\node_modules\ >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
robocopy /nfl /ndl /E %~dp0node_modules\ %WWW_FRONTEND_BASE_DIRECTORY%\node_modules\ >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net start QuickQuotation_FrontEnd(8000) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net start QuickQuotation_FrontEnd(8000) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net start QuickQuotation_FrontEnd(8001) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net start QuickQuotation_FrontEnd(8001) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net start QuickQuotation_FrontEnd(8002) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net start QuickQuotation_FrontEnd(8002) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1

@ECHO net start QuickQuotation_FrontEnd(8003) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
net start QuickQuotation_FrontEnd(8003) >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
 
GOTO END
 
:NO_WWW_FRONTEND_BASE_DIRECTORY
@ECHO The NO_WWW_FRONTEND_BASE_DIRECTORY environment variable was NOT detected. >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1
 

GOTO END
:END
@ECHO BatchFinished... >> %AUTOMATIC_BATCH_INSTALLER_LOG_FILE% 2>&1