SET LOGPATH=%~1\
SET TEST_ERROR=0
SET BUILD_ERROR=0
SET COMPDIST_ERROR=0

REM ADDING NODE/NPM PATH
SET PATH=%USERPROFILE%\AppData\Roaming\npm;C:\Program Files\nodejs;%PATH%

REM FIRST PARAMETER IS THE OUTPUT DIR
IF "%~1"=="" SET LOGPATH=%USERPROFILE%\Desktop\
ECHO START > %LOGPATH%\echo_log.txt
ECHO =============================== >> %LOGPATH%\echo_log.txt
ECHO PATH >> %LOGPATH%\echo_log.txt
ECHO %PATH% >> %LOGPATH%\echo_log.txt
ECHO =============================== >> %LOGPATH%\echo_log.txt

REM GRUNT TEST
CALL grunt test 1> %LOGPATH%\grunt_test_log.txt 2>&1  
ECHO GRUNT TEST RETURNS %ERRORLEVEL% >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% GTR 0 (
SET /A TEST_ERROR=%ERRORLEVEL%*1000
)

REM GRUNT BUILD
CALL grunt build 1> %LOGPATH%\grunt_build_log.txt 2>&1 
ECHO GRUNT BUILD RETURNS %ERRORLEVEL% >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% GTR 0 (
SET /A BUILD_ERROR=%ERRORLEVEL%*100
)

REM GRUNT COMPDIST
CALL grunt compDist 1> %LOGPATH%\grunt_compDist_log.txt 2>&1 
ECHO GRUNT COMPDIST RETURNS %ERRORLEVEL% >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% GTR 0 (
SET /A COMPDIST_ERROR=%ERRORLEVEL%*10
)

REM SKIP ERROR
GOTO END

:ERROR
ECHO ERROR(S) OCCUR(S) LEVEL IS : %ERRORLEVEL% >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 1 ECHO GRUNT - FATAL ERROR >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 2 ECHO GRUNT - MISSING GRUNTFILE ERROR >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 3 ECHO GRUNT - TASK ERROR >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 4 ECHO GRUNT - TEMPLATE PROCESSING ERROR >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 5 ECHO GRUNT - INVALID SHELL AUTO-COMPLETION RULES ERROR >> %LOGPATH%\echo_log.txt 
IF %ERRORLEVEL% EQU 6 ECHO GRUNT - WARNING >> %LOGPATH%\echo_log.txt 


ECHO SKIPPING NEXT STATEMENT... >> %LOGPATH%\echo_log.txt 
GOTO END
:END
IF %ERRORLEVEL% EQU 0 ECHO BATCH - SUCCEED >> %LOGPATH%\echo_log.txt 
SET /A TOTAL_ERROR=%TEST_ERROR%+%BUILD_ERROR%+%COMPDIST_ERROR%
EXIT /B %TOTAL_ERROR%

REM GRUNT ERROR CODES
REM 0 - NO ERRORS!
REM 1 - FATAL ERROR
REM 2 - MISSING GRUNTFILE ERROR
REM 3 - TASK ERROR
REM 4 - TEMPLATE PROCESSING ERROR
REM 5 - INVALID SHELL AUTO-COMPLETION RULES ERROR
REM 6 - WARNING